### PR TITLE
debugging features

### PR DESCRIPTION
**Pull request by Raynos**
Thanks for building this package, super easy way to get started
with `tape` and `puppeteer`.

I found some developer experience improvements around
debugging that are useful for me.

 - Add `--autoclose` parameter so that `tape-puppet` can keep
    the chrome browser open for further debugging
 - Add `--debug` for breakpoint at the start; kind of like how
    node used to have `--debug-brk` to start the program paused
 - Updated to puppeteer@2.0.0 for latest chrome
 - Use `addScriptTag` instead of `evaluate` to allow for
    debugging exceptions in devtools in the initial script.
 - Add more `console.error` ; there were a bunch of `err` that
    were just silently not being logged anywhere and `tape-puppet`
    would just exit ( with code 0 ) instead.

### CODE REVIEW

**Comment by Raynos** [comment]
@chiefbiiko Would you like to take a look at these additions ? Let me know if they are useful for you.

**Comment by chiefbiiko** [comment]
thanks for the exit code fix and these ux additions! cool!

**Comment by Raynos** [comment]
If you can published a new version that would be great :)

**Comment by Raynos** [comment]
@chiefbiiko

```
npm version patch && git push origin master --tags && npm publish
``` 

Can you publish a new patch ? :D

**Comment by chiefbiiko** [comment]
@Raynos sorry, thanks, done 📼 📦 🏷

**Pull request merged**
